ALTER TABLE
  wiki_folders
  ADD
    is_root BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE
  wiki_pages
  ALTER COLUMN
    parent_folder_fk_id TYPE INT,
  ALTER COLUMN
    parent_folder_fk_id
    SET
    NOT NULL;

CREATE UNIQUE INDEX uq_wiki_root_folder ON wiki_folders (wiki_id)
  WHERE
    wiki_folders.is_root = TRUE;

-- Checks aren't generated by exposed so I had to write this.
ALTER TABLE wiki_folders
  ADD CONSTRAINT wiki_folders_root_parent_consistency
    CHECK (
      (is_root = TRUE  AND parent_folder_id IS NULL) OR
      (is_root = FALSE AND parent_folder_id IS NOT NULL)
);